FROM abesnier/php-fpm:grav-alpine

COPY --from=ghcr.io/php/pie:bin /pie /usr/bin/pie

RUN apk add --update --no-cache yaml-dev \
&& apk add --update --no-cache --virtual .build-dependencies $PHPIZE_DEPS linux-headers\
&& pie install apcu/apcu \
&& pie install pecl/yaml \
&& pie install xdebug/xdebug \
&& docker-php-ext-enable apcu yaml xdebug opcache\
&& apk del .build-dependencies linux-headers
